mysite/mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from schoolsite import views
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('schoolsite.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/schoolsite/urls.py
from django.conf.urls import url
from . import views

app_name = 'schoolsite'

urlpatterns = [
    # /
    url(r'^$', views.home , name='home'),
    # /aanbod/
    url(r'^aanbod/$', views.aanbod, name='aanbod'),
    # /leraren/
    url(r'^leraren/$', views.leraren, name='leraren'),
    # /contact/
    url(r'^contact/', views.contact, name='contact'),
    # /intranet/
    url(r'^intranet/$', views.intranet, name='intranet'),
    # /intranet/new-course
    url(r'^intranet/new-course/$', views.new_course, name='new_course'),
    # /intranet/new-teacher
    url(r'^intranet/new-teacher/$', views.new_teacher, name='new_teacher'),
    # /intranet/edit-course
    url(r'^intranet/edit-course/$', views.edit_course, name='edit_course'),
    # /intranet/edit-teacher
    url(r'^intranet/edit-teacher/$', views.edit_teacher, name='edit_teacher'),
    # # /intranet/delete-course
    url(r'^intranet/delete-course-(?P<id>[0-9]+)/$', views.delete_course, name='delete_course'),
    # # /intranet/delete-teacher
    url(r'^intranet/delete-teacher-(?P<id>[0-9]+)/$', views.delete_teacher, name='delete_teacher'),
    # /login/
    url(r'^login/', views.login, name='login'),
    # /logout/
    url(r'^logout/$', views.logout, name='logout'),
]

mysite/schoolsite/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Course(models.Model):
    course_name = models.CharField(max_length=50)
    course_desc = models.CharField(max_length=250)

class Teacher(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    details = models.CharField(max_length=100)
    email = models.CharField(max_length=50)
    image = models.FileField(blank=True, null=True)

    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url

class Contact(models.Model):
    contact_name = models.CharField(max_length=30)
    contact_email = models.CharField(max_length=50)
    contact_message = models.CharField(max_length=500)
    #form

class Login(models.Model):
    login_name = models.CharField(max_length=50)
    login_pw = models.CharField(max_length=200)
    #form

mysite/schoolsite/forms.py
from django import forms
from django.forms import ModelForm, Textarea
from .models import Contact
from .models import Login
from .models import Course
from .models import Teacher
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout



class SubmitForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = (
            "contact_name",
            "contact_email",
            "contact_message",
        )
        labels = {
            'contact_name': "Volledige naam",
            'contact_email' : "E-mail",
            'contact_message' : "Bericht",
        }

class newCourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = (
            "course_name",
            "course_desc",
        )
        labels = {
            'course_name': "Richting naam",
            'course_desc' : "Richting beschrijving",
        }

class newTeacherForm(forms.ModelForm):
   
    class Meta:
        model = Teacher
        fields = (
            "first_name",
            "last_name",
            "details",
            "email",
            "image",
        )
        labels = {
            'first_name': "Voornaam",
            'last_name' : "Achternaam",
            'details' : "Details",
            'email' : "Email",
            'image' : "Foto",
        }

class SubmitLogin(forms.ModelForm):
    login_pw = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = Login
        fields = (
            "login_name",
            "login_pw",
        )
        labels = {
            'login_name': "Gebruikersnaam",
            'login_pw': "Wachtwoord",
        }
    

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("login_name")
        password = self.cleaned_data.get("login_pw")
        
        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("Deze gebruiker bestaat niet")
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect paswoord")
            if not user.is_active:
                raise forms.ValidationError("Deze gebruiker is niet meer actief")
        return super(SubmitLogin, self).clean(*args, **kwargs)

mysite/schoolsite/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .models import Teacher
from .models import Course
from .models import Contact
from .models import Login
from .forms import SubmitForm
from .forms import SubmitLogin
from .forms import newCourseForm
from .forms import newTeacherForm

import datetime



# Create your views here.
def home(request):
    currentTime = datetime.datetime.now()
    currentTime.hour
 
    if currentTime.hour < 12:
        time = "Goedemorgen"

    elif 12 <= currentTime.hour < 18:
        time="Goedemiddag"
    else:
        time="Goedenavond"

        #if request.user.is_authenticated():
        #time = "hello " + request.user.username
    if not request.COOKIES.get('visit'):
        context = {'time': time}
        response = render(request, 'schoolsite/index.html', context)
        response.set_cookie('visit', 'true')
        return response
    else:
        welcome = "Welkom terug"
        context = ({'time': time, 'welcome':welcome}) 
        response = render(request, 'schoolsite/index.html', context)
        response.set_cookie('visit', 'true')
        return response

def aanbod(request):
    all_courses = Course.objects.all()
    context = {'all_courses': all_courses}
    return render(request, 'schoolsite/courses.html', context)

def leraren(request):
    all_teachers = Teacher.objects.all()
    context = {'all_teachers': all_teachers}
    return render(request, 'schoolsite/teachers.html', context)

def contact(request):
    if request.method == "POST":
       form = SubmitForm(request.POST or None)
       if form.is_valid():
          instance = form.save(commit=False)
          instance.save()
          return redirect('/')
    else:
        form = SubmitForm()
    return render(request, 'schoolsite/contact.html', {'form': form})

def intranet(request):
    all_teachers = Teacher.objects.all()
    all_courses = Course.objects.all()
    return render(request, 'schoolsite/intranet.html', {'all_teachers': all_teachers, 'all_courses': all_courses})

def login(request):
    if request.method == "POST":
       form = SubmitLogin(request.POST or None)
       if form.is_valid():
          username = form.cleaned_data.get("login_name")
          password = form.cleaned_data.get("login_pw")
          user = authenticate(username=username, password=password)
          if user is not None:
              if user.is_active:
                  auth_login(request, user)
          return redirect('/')
    else:
        form = SubmitLogin()
    return render(request, 'schoolsite/login.html', {'form': form})

def logout(request):
    auth_logout(request)
    return render(request, 'schoolsite/index.html')

def new_course(request):
    if request.method == "POST":
       form = newCourseForm(request.POST or None)
       if form.is_valid():
          instance = form.save(commit=False)
          instance.save()
          return redirect('schoolsite/intranet.html')
    else:
        form = newCourseForm()
    return render(request, 'schoolsite/new-course.html', {'form': form})

def new_teacher(request):
    if request.method == "POST":
       form = newTeacherForm(request.POST or None)
       if form.is_valid():
          instance = form.save(commit=False)
          instance.save()
          return redirect('/intranet') 
    else:
        form = newTeacherForm()
    return render(request, 'schoolsite/new-teacher.html', {'form': form})

def edit_course(request):
    if request.method == "POST":
       form = newCourseForm(request.POST or None)
       if form.is_valid():
          instance = form.save(commit=False)
          instance.save()
          return redirect('schoolsite/intranet.html')
    else:
        form = newCourseForm()
    return render(request, 'schoolsite/edit-course.html', {'form': form})

def edit_teacher(request):
    if request.method == "POST":
       form = newTeacherForm(request.POST or None)
       if form.is_valid():
          instance = form.save(commit=False)
          instance.save()
          return redirect('schoolsite/intranet.html')
    else:
        form = newTeacherForm()
    return render(request, 'schoolsite/edit-teacher.html', {'form': form})

def delete_course(request):
    instance = get_object_or_404(Course, id=id)
    instance.delete()
    return redirect('schoolsite/intranet.html')

def delete_teacher(request):
    instance = get_object_or_404(Teacher, id=id)
    instance.delete()
    return redirect('schoolsite/intranet.html')

mysite/schoolsite/templates/schoolsite/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}SCHOOLSITE{% endblock %}</title>
    
    <!-- Bootstrap core CSS -->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  
    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="{% static 'schoolsite/css/heroic-features.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'schoolsite/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'schoolsite/css/style.css' %}" />

  </head>
  <body>

    <!-- Navigation -->
    {% if user.is_authenticated %}
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
          <a class="navbar-brand" href="/">SCHOOLSITE</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="/">Home
                  <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/aanbod">Aanbod</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/leraren">Wie is wie</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/contact">Contact</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/intranet">Intranet</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/logout">Logout</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    
    {% else %}
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
          <a class="navbar-brand" href="/">SCHOOLSITE</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="/">Home
                  <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/aanbod">Aanbod</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/leraren">Wie is wie</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/contact">Contact</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/login">Login</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    
    {% endif %}
    
    
    <!-- Page Content -->
    {% block body %}
    {% endblock %}
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; SCHOOLSITE DIETER ENGELS 2017</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="static/schoolsite/js/jquery.min.js"></script>
    <script src="static/schoolsite/js/bootstrap.bundle.min.js"></script>

  </body>
</html>

mysite/schoolsite/templates/schoolsite/contact.html
{% extends 'schoolsite/base.html' %}

{% block title %}Contact{% endblock %}

{% block body %}
{% load widget_tweaks%}

<!-- Page Content -->
<div class="container formcontainer">
    <div class="col-md-6 form1">
        <div class="form-area">  
            <form role="form" method="POST" action="/contact/">
                <br style="clear:both">
                <h3>Onze contactgegevens</h3>
                <p>
                    Besteschoollaan 100<br>
                    2000 Antwerpen<br>
                    +32(0)3 666 13 37
                </p>
                <h3 style="margin-bottom: 25px; text-align: center;">Contact Formulier</h3>
                {% csrf_token %} {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %} {% for field in form.visible_fields %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field|add_class:'form-control' }} {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                </div>
                {% endfor %}
                <div class="form-group">
                    <button type="submit" id="submit" name="submit" class="btn btn-primary pull-left">Verstuur</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /.container -->
{% endblock %}

mysite/schoolsite/templates/schoolsite/courses.html
{% extends 'schoolsite/base.html' %}

{% block title %}Aanbod{% endblock %}

{% block body %}
    <!-- Page Content -->
    <div class="container">

      <!-- Jumbotron Header -->
      <header class="jumbotron my-4">
        <h2 class="display-3"><strong>Welke richtingen heeft onze school te bieden</strong></h2>
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, ipsam, eligendi, in quo sunt possimus non incidunt odit vero aliquid similique quaerat nam nobis illo aspernatur vitae fugiat numquam repellat.</p>
      </header>

      

      <!-- Page Features -->
      <div class="row text-center">
        {% for course in all_courses %}
        
        <div class="col-lg-3 col-md-6 mb-4">
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title">{{ course.course_name }}</h4>
                    <p class="card-text">{{ course.course_desc }}</p>
                  </div>
                </div>
        </div>

        {% endfor %}

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->
    
{% endblock %}

mysite/schoolsite/templates/schoolsite/edit-course.html
{% extends 'schoolsite/base.html' %}

{% block title %}Edit Richting{% endblock %}

{% block body %}
{% load widget_tweaks%}

<!-- Page Content -->
<div class="container formcontainer">
    <div class="col-md-6 form1">
        <div class="form-area">  
            <form role="form" method="POST" action="/intranet/" enctype="multipart/form-data">
                <br style="clear:both">
                <h3 style="margin-bottom: 25px; text-align: center;">Edit Richting</h3>
                {% csrf_token %} {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %} {% for field in form.visible_fields %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field|add_class:'form-control' }} {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                </div>
                {% endfor %}
                <div class="form-group">
                    <button type="submit" id="submit" name="submit" class="btn btn-success pull-left">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /.container -->
{% endblock %}

mysite/schoolsite/templates/schoolsite/edit-teacher.html
{% extends 'schoolsite/base.html' %}

{% block title %}Edit Leerkracht{% endblock %}

{% block body %}
{% load widget_tweaks%}

<!-- Page Content -->
<div class="container formcontainer">
    <div class="col-md-6 form1">
        <div class="form-area">  
            <form role="form" method="POST" action="/intranet/" enctype="multipart/form-data">
                <br style="clear:both">
                <h3 style="margin-bottom: 25px; text-align: center;">Edit Leerkracht</h3>
                {% csrf_token %} {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %} {% for field in form.visible_fields %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field|add_class:'form-control' }} {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                </div>
                {% endfor %}
                <div class="form-group">
                    <button type="submit" id="submit" name="submit" class="btn btn-success pull-left">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /.container -->
{% endblock %}

mysite/schoolsite/templates/schoolsite/index.html
{% extends 'schoolsite/base.html' %}

{% block title %}Home{% endblock %}

{% block body %}

    <div class="container">
        <!-- Jumbotron Header -->
        <header class="jumbotron my-4">
            <h1 class="display-3">{{time}}. {{welcome}}</h1>
            <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, ipsam, eligendi, in quo sunt possimus non incidunt odit vero aliquid similique quaerat nam nobis illo aspernatur vitae fugiat numquam repellat.</p>
        </header>

        <!-- Page Features -->
        <div class="row text-center">

            <div class="col-lg-3 col-md-6 mb-4">
            <div class="card">
                <img class="card-img-top" src="http://placehold.it/500x325" alt="">
                <div class="card-body">
                <h4 class="card-title">Artikel 1</h4>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
                </div>
                <div class="card-footer">
                <a href="#" class="btn btn-primary">Find Out More!</a>
                </div>
            </div>
            </div>

            <div class="col-lg-3 col-md-6 mb-4">
            <div class="card">
                <img class="card-img-top" src="http://placehold.it/500x325" alt="">
                <div class="card-body">
                <h4 class="card-title">Artikel 2</h4>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo magni sapiente, tempore debitis beatae culpa natus architecto.</p>
                </div>
                <div class="card-footer">
                <a href="#" class="btn btn-primary">Find Out More!</a>
                </div>
            </div>
            </div>

            <div class="col-lg-3 col-md-6 mb-4">
            <div class="card">
                <img class="card-img-top" src="http://placehold.it/500x325" alt="">
                <div class="card-body">
                <h4 class="card-title">Artikel 3</h4>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
                </div>
                <div class="card-footer">
                <a href="#" class="btn btn-primary">Find Out More!</a>
                </div>
            </div>
            </div>

            <div class="col-lg-3 col-md-6 mb-4">
            <div class="card">
                <img class="card-img-top" src="http://placehold.it/500x325" alt="">
                <div class="card-body">
                <h4 class="card-title">Artikel 4</h4>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo magni sapiente, tempore debitis beatae culpa natus architecto.</p>
                </div>
                <div class="card-footer">
                <a href="#" class="btn btn-primary">Find Out More!</a>
                </div>
            </div>
            </div>

        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->

{% endblock %}

mysite/schoolsite/templates/schoolsite/intranet.html
{% extends 'schoolsite/base.html' %}

{% block title %}Intranet{% endblock %}

{% block body %}

    <!-- Page Content -->
    <div class="container">

      <!-- Jumbotron Header -->
      <header class="jumbotron my-4">
            <h2 class="display-3"><strong>INTRANET</strong></h2>
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, ipsam, eligendi, in quo sunt possimus non incidunt odit vero aliquid similique quaerat nam nobis illo aspernatur vitae fugiat numquam repellat.</p>
      </header>
      <!-- Page Features -->
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">PK</th>
            <th scope="col">Richting naam</th>
            <th scope="col">Richting beschrijving</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for course in all_courses %}
          <tr>
            <td>{{ course.pk }}</td>
            <td>{{ course.course_name }}</td>
            <td>{{ course.course_desc }}</td>
            <td>
                <a href="edit-course" class="btn btn-warning a-btn-slide-text">
                    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                    <span><strong>Edit</strong></span>            
                </a>
                <form action="{% url 'schoolsite:delete_course' course.id %}">
                  <a href="intranet" class="btn btn-danger a-btn-slide-text">
                      <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                      <span><strong>Delete</strong></span>            
                  </a>
                </form>
            </td>
          </tr>
        </tbody>
        {% endfor %}
      </table>
      <a href="new-course" class="btn btn-primary a-btn-slide-text">
          <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
          <span><strong>Add</strong></span>            
      </a>
      <br>
      <br>
      <table class="table">
          <thead class="thead-dark">
            <tr>
              <th scope="col">PK</th>
              <th scope="col">Leerkracht voornaam</th>
              <th scope="col">Leerkracht achternaam</th>
              <th scope="col">Leerkracht email</th>
              <th scope="col">Leerkracht beschrijving</th>
              <th scope="col">Leerkracht foto</th>
              <th scope="col">Actions</th>
            </tr>
          </thead>
          <tbody>
            {% for teacher in all_teachers %}
            <tr>
              <td>{{ teacher.pk }}</td>
              <td>{{ teacher.first_name }}</td>
              <td>{{ teacher.last_name }}</td>
              <td>{{ teacher.email }}</td>
              <td>{{ teacher.details }}</td>
              <td><img class="card-img-top img-responsive img-thumbnail" style="width:10%" src="{{ teacher.image_url|default_if_none:'#' }}"> {{ teacher.image }}</td> <!-- src="{{ teacher.image.url }}"> -->
              <td>
                  <a href="edit-teacher" class="btn btn-warning a-btn-slide-text">
                      <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                      <span><strong>Edit</strong></span>            
                  </a>
                  <form action="{% url 'schoolsite:delete_teacher' teacher.id %}">
                      <a href="intranet" class="btn btn-danger a-btn-slide-text">
                          <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                          <span><strong>Delete</strong></span>            
                      </a>
                  </form>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        <a href="new-teacher" class="btn btn-primary a-btn-slide-text">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            <span><strong>Add</strong></span>            
        </a>
    </div>
    <br>
    <!-- /.container -->
{% endblock %}

mysite/schoolsite/templates/schoolsite/login.html
{% extends 'schoolsite/base.html' %}

{% block title %}Contact{% endblock %}

{% block body %}
{% load widget_tweaks%}

<!-- Page Content -->
<div class="container formcontainer">
    <div class="col-md-6 form1">
        <div class="form-area">  
            <form role="form" method="POST" action="login/">
                <br style="clear:both">
                <h3 style="margin-bottom: 25px; text-align: center;">Login in je account</h3>
                {% csrf_token %} {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %} {% for field in form.visible_fields %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field|add_class:'form-control' }} {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                </div>
                {% endfor %}
                <div class="form-group">
                    <button type="submit" id="submit" name="submit" class="btn btn-primary pull-left">Login</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /.container -->
{% endblock %}

mysite/schoolsite/templates/schoolsite/new-course.html
{% extends 'schoolsite/base.html' %}

{% block title %}Nieuwe Richting{% endblock %}

{% block body %}
{% load widget_tweaks%}

<!-- Page Content -->
<div class="container formcontainer">
    <div class="col-md-6 form1">
        <div class="form-area">  
            <form role="form" method="POST" action="/intranet/" enctype="multipart/form-data">
                <br style="clear:both">
                <h3 style="margin-bottom: 25px; text-align: center;">Nieuwe Richting</h3>
                {% csrf_token %} {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %} {% for field in form.visible_fields %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field|add_class:'form-control' }} {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                </div>
                {% endfor %}
                <div class="form-group">
                    <button type="submit" id="submit" name="submit" class="btn btn-success pull-left">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /.container -->
{% endblock %}

mysite/schoolsite/templates/schoolsite/new-teacher.html
{% extends 'schoolsite/base.html' %}

{% block title %}Nieuwe Leerkracht{% endblock %}

{% block body %}
{% load widget_tweaks%}

<!-- Page Content -->
<div class="container formcontainer">
    <div class="col-md-6 form1">
        <div class="form-area">  
            <form role="form" method="POST" action="/intranet/new-teacher/" enctype="multipart/form-data">
                <br style="clear:both">
                <h3 style="margin-bottom: 25px; text-align: center;">Nieuwe Leerkracht</h3>
                {% csrf_token %} {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %} {% for field in form.visible_fields %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field|add_class:'form-control' }} {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                </div>
                {% endfor %}
                <div class="form-group">
                    <button type="submit" id="submit" name="submit" class="btn btn-success pull-left">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- /.container -->
{% endblock %}